### ISSUE TITLE
Phaser not displaying on Android

### ISSUE THREAD

**Issue by afokt** [openforge/ionic-phaser-game-template#35]
Really appreciate your work on doing a sample reusable template for integrated use of Ionic & Angular & Phaser with good working Nx tool for maintaining monorepo structure.

Your template app is working well in browser out-of-the-box (via 'nx serve example-app').

However, built for Android (via the standard set of commands below):
```
npm install --save-dev --exact @nxtend/capacitor
nx generate @nxtend/capacitor:capacitor-project --appName=ionic-phaser-demo --project=example-app
nx build example-app --configuration development
cd apps/example-app
npm install

nx run example-app:add --configuration android
nx run example-app:open --configuration android
```

The game canvas is not visible (i.e. only a small size of black square gets rendered, and I cannot find out, why).

The issue presents both on emulator as well as on physical device (on all the Android versions I tested with),
meanwhile, by using capacitor the same way for '[openfarm-puzzle-game](https://github.com/openforge/openfarm-puzzle-game)'  (not Nx monorepo based project), that also works right on Android as well.

(Or am I misusing capacitor here?)

![kép](https://user-images.githubusercontent.com/24968978/187266243-7d21ebed-9598-4c97-be4c-ad68ea1537a9.png)

**Comment by Ricardo385** [comment]
Hey @afokt! We are so sorry for the very late response! We have resumed the work in this template and we have make the necessary updates to make it work again with the latest! Please, pull latest changes from `master` branch and follow the README instructions. The issue you mentioned above has been fixed and tested, now the app is working correctly both in Android and iOS. Have fun :) Best Regards.
